Add scripts for grid aggregation
equinor/xtgeoapp-grd3dmaps pull request #58
Opened 2022-05-30 18:33 UTC by vegardkv

Two scripts are added with corresponding tests and documentation:
- grid3d_aggregate_map: general grid aggregation (min/max/mean/sum)
- grid3d_migration_time: co2 plume migration time map generation

Issues that might require attention before merge:
- fmu-dataio is not implemented for these two scripts. Attempting to use it via the "fmu-dataio" magic keyword will raise an exception.
- Some keywords and features supported by `grid3d_average_map` and `grid3d_hc_thickness` are not supported by these two scripts. Some of these are "filters", "computesettings/mask_outside", "!"-YAML macros (!include/include_from), "zonation/yamlfile". Any keywords provided by the user, but not supported will result in an exception being raised.
- Specifying input parameters has two significant differences from the two existing scripts:
  - Properties _must_ be provided under the _properties_ keyword in the _input_ section of the file. Properties cannot be given directly under _input_
  - A property lower threshold can be provided for each property via the `lower_threshold` keyword. This is technically a performance-related setting, and should perhaps be moved to `computesettings`, similar to e.g. `shcinterval`. However, moving it to `computesettings` means we need to link it to a property via name or apply it to all properties.
- Maps are always "masked outside". Providing `mask_outside` under `computesettings` is not supported. If we want to enable this as an option, it should probably also include a way of setting the outside value (to something else than e.g. a default 0.0).
- Changes to documentation are included, but these may require further polishing.

2022-06-10 09:34 UTC, jcrivenaes commented
The tests for aggegate are not working, e.g. `test_submodules/test_grid_aggregate.py`' asks for `from xtgeoapp_grd3dmaps.aggregate import aggregate_maps` which does not exist. Could you endure that tests are working before I review further? (There are some other tests now faileing; I will take a look on that)

2022-06-13 10:59 UTC, vegardkv commented
Tests should be working now, but some of the errors in previous checks was caused by an error message by pip: "Error: The operation was canceled.". This was likely a typo in setup.py that is now fixed, but the final test probably needs to be done here.

2022-06-17 13:03 UTC, jcrivenaes commented
github actions in master is now updated; include that change, rerun and see if that helps

2022-06-20 19:26 UTC, jcrivenaes commented on docs/howitworks.rst
> +This is not applicable to grid3d_aggregate_map and grid3d_migration_time,
It would be nice with some short summary of what the difference is, if possible

2022-06-20 19:33 UTC, jcrivenaes commented on tests/test_submodules/test_grid_aggregate.py
> +        np.linspace(-100, 100, 21),
pylint is complaining here on "redfeining name ... from outer scope... rather use:
```
@pytest.fixture(name="example_grid")
def fixture_example_grid():
    """Use a docstring also to describe shortly."""

```
And put the fixures in the top of the file perhaps

2022-06-20 19:34 UTC, jcrivenaes commented on tests/test_submodules/test_grid_aggregate.py
> +    z = np.array([100, 107, 114, 128])
Avoid one-letter variables if possible; I usually prefer minimum 3 letters (makes any later refactoring easier)

2022-06-20 19:37 UTC, jcrivenaes commented
I will continue tomorrow...

2022-06-22 18:22 UTC, jcrivenaes reviewed
I am not able to build documentation with examples:
```
$ python setup.py build_sphinx
/home/jan/venv/3.8_xtgeoapp_grd3dmaps/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  warnings.warn(
/usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'extras_requires'
  warnings.warn(msg)
running build_sphinx
Running Sphinx v3.5.4
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] examples                                                                                                                                                                                                                   
/home/jan/work/git/xtg/xtgeoapp-grd3dmaps/docs/examples.rst:278: WARNING: Include file '/home/jan/work/git/xtg/xtgeoapp-grd3dmaps/docs/test_to_docs/aggregate1.yml' not found or reading it failed
/home/jan/work/git/xtg/xtgeoapp-grd3dmaps/docs/examples.rst:287: WARNING: Include file '/home/jan/work/git/xtg/xtgeoapp-grd3dmaps/docs/test_to_docs/aggregate2.yml' not found or reading it failed
/home/jan/work/git/xtg/xtgeoapp-grd3dmaps/docs/examples.rst:295: WARNING: Include file '/home/jan/work/git/xtg/xtgeoapp-grd3dmaps/docs/test_to_docs/aggregate3.yml' not found or reading it failed
/home/jan/work/git/xtg/xtgeoapp-grd3dmaps/docs/examples.rst:303: WARNING: Include file '/home/jan/work/git/xtg/xtgeoapp-grd3dmaps/docs/test_to_docs/aggregate4.yml' not found or reading it failed
/home/jan/work/git/xtg/xtgeoapp-grd3dmaps/docs/examples.rst:313: WARNING: Include file '/home/jan/work/git/xtg/xtgeoapp-grd3dmaps/docs/test_to_docs/aggregate5.yml' not found or reading it failed
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                                                                                                                                                                                       
generating indices... genindex done
writing additional pages... search done
copying images... [100%] test_to_docs/z3--avg1b_average_por.png                                                                                                                                                                                      
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 5 warnings.


```
Are you missing the mechanism that is included in eg. `tests/test_scripts/test_grid3d_hc_thickness_dataio1a.py` ?(see bottom of this file)

2022-06-22 18:25 UTC, jcrivenaes requested changes
Pleas run pylint on the code and resolve:

`pylint src/xtgeoapp_grd3dmaps/aggregate`

2022-06-24 14:06 UTC, vegardkv commented
Fixed most of the issues and used the opportunity to clean up a bit. There are still some issues remaining:
- pylint not completely satisfied
- documentation is not complete

Will continue after the weekend

2022-06-29 07:46 UTC, merged